name: CI/CD Amplify

on:
  push:
    branches:
      - main  # déclenchement automatique sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code du repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3️⃣ Installer les dépendances du projet
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build de l'application React
      - name: Build React app
        run: npm run build

      # 5️⃣ Configurer AWS via OIDC et rôle IAM
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::319094876562:role/Demo-GithubAction-Amplify
          aws-region: eu-west-3

      # 6️⃣ Installer Amplify CLI et publier sur Amplify
      - name: Publish to Amplify
        run: npx @aws-amplify/cli publish --yes
